name: Run Screener

on:
  schedule:
    # Weekdays 09:00 Asia/Taipei (UTC-8 in winter / UTC-8?). GitHub cron uses UTC; 01:00 UTC ≈ 09:00 Taipei (UTC+8)
    - cron: '0 1 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run screener
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python screener.py
