name: Run Interactive Slack Bot

on:
  workflow_dispatch: {} # 允許手動觸發

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Interactive Bot
        env:
          # 需要 App-Level Token 和 Bot Token
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          if [ -z "$SLACK_APP_TOKEN" ] || [ -z "$SLACK_BOT_TOKEN" ]; then
            echo "::error::SLACK_APP_TOKEN and SLACK_BOT_TOKEN secrets must be set."
            exit 1
          fi
          python interactive_bot.py